### ISSUE TITLE
What's up with appointment slot types?

### ISSUE THREAD

**Issue by gausie** [UCLU/appointment#1]

**Comment by pjcdawkins** [comment]
You mean what's the reason for them? Customisable fields etc

**Comment by gausie** [comment]
I was just wondering as they seem to be hard coded without the possibility
to hook_alter or anything.

**Comment by pjcdawkins** [comment]
Oh yeah well maybe that would have been more useful!

**Comment by gausie** [comment]
Ok! Was just wondering if I was misunderstanding how it should be used :)
